packages:
  - "packages/social-pixl-sdk"
  - "packages/social-pixl-sdk-v2"
  - "packages/nc-gui"
  - "packages/nc-mail-templates"
  - "packages/nocodb"
  - "tests/playwright"
  - "packages/nc-secret-mgr"
